//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import Foundation;
@import IOBluetooth;

struct IOBluetoothHCIEventNotificationMessage;
typedef struct IOBluetoothHCIEventNotificationMessage * IOBluetoothHCIEventNotificationMessageRef;

NS_ASSUME_NONNULL_BEGIN

@protocol IOBluetoothHostControllerDelegate
@end

struct BluetoothHCIUserClientNotificationDataInfo {
    unsigned long long _field1;
    unsigned long long _field2;
    struct BluetoothHCIRequestCallbackInfo _field3;
    unsigned int parameterSize;
    unsigned int _field5;
    unsigned short opcode;
    unsigned char _field7;
    unsigned char _field8;
    unsigned char _field9;
    unsigned char _field10;
    unsigned char _field11;
    unsigned char _field12;
};

struct IOBluetoothHCIEventNotificationMessage {
    struct BluetoothHCIUserClientNotificationDataInfo dataInfo;
    void *eventParameterBytes;
};

int BluetoothHCIRequestCreate(uint32_t *request, int timeout, void* arg3, size_t arg4);

int BluetoothHCIRequestDelete(uint32_t request);

int BluetoothHCISendRawCommand(uint32_t request,
                               void *commandData,
                               size_t commmandSize);

int BluetoothHCISendRawACLData(void *commandData,
                               size_t commandSize,
                               uint32_t handle,
                               uint32_t request);

/**
 Data object for notification message.
 */
static inline NSData * IOBluetoothHCIEventParameterData(IOBluetoothHCIEventNotificationMessageRef message)
//__attribute__((swift_name("getter:IOBluetoothHCIEventNotificationMessageRef.eventParameterData(self:)")))
{
    size_t size = message->dataInfo.parameterSize;
    NSData *data = [NSData dataWithBytes:&message->eventParameterBytes length:size];
    return data;
}

NS_ASSUME_NONNULL_END
